/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectozapatosirving;
// --- IMPORTACIONES NECESARIAS ---
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
// (Asegúrate de tener la librería JCalendar agregada a tu proyecto)

/**
 *
 * @author amox_
 */
public class Ventas extends javax.swing.JPanel {


    // --- VARIABLES GLOBALES ---
    private Connection con;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
        
        // 1. Conectar a la BD
        this.con = Conexion.getConexion();
        
        // 2. Obtener el modelo de la tabla
        this.modeloTabla = (DefaultTableModel) tablaVentasDia.getModel();
        
        // 3. Configurar campos
        txtTotalDia.setEditable(false);
        
        // 4. Poner la fecha de hoy en el JDateChooser por defecto
        // (Usando el nombre de tu variable: JDateChooser)
        JDateChooser.setDate(new java.util.Date());
        
        // 5. Asignar el evento al botón
        // (Usando el nombre de tu variable: CALCULAR)
        CALCULAR.addActionListener(e -> calcularCorte());
        
        // 6. Cambiar texto del botón (opcional, pero recomendado)
        CALCULAR.setText("Calcular Corte");
    }

    /**
     * Calcula el total de ventas para la fecha seleccionada
     */
    private void calcularCorte() {
        // 1. Obtener la fecha del JDateChooser
        java.util.Date fechaUtil = JDateChooser.getDate();
        
        if (fechaUtil == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha válida.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Convertir de java.util.Date a java.sql.Date
        long ms = fechaUtil.getTime();
        java.sql.Date fechaSql = new java.sql.Date(ms);

        // 3. Limpiar la tabla y el total anterior
        modeloTabla.setRowCount(0);
        double granTotal = 0;

        // 4. Preparar la consulta SQL
        // Usamos la función DATE() de MySQL para comparar solo la parte de la fecha
        // Tu tabla usa "FOLIO", "FECHA/HORA", "TOTAL"
        String sql = "SELECT venta_id, fecha, total FROM ventas WHERE DATE(fecha) = ?";
        
        try (PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setDate(1, fechaSql); // Asignamos la fecha al parámetro

            try (ResultSet rs = ps.executeQuery()) {
                
                // 5. Recorrer los resultados
                while (rs.next()) {
                    int idVenta = rs.getInt("venta_id");
                    Timestamp fechaHora = rs.getTimestamp("fecha"); // Obtenemos fecha y hora
                    double totalVenta = rs.getDouble("total");
                    
                    // 5a. Acumular el gran total
                    granTotal += totalVenta;
                    
                    // 5b. Agregar la fila a la tabla
                    modeloTabla.addRow(new Object[]{
                        idVenta,              // Columna FOLIO
                        fechaHora.toString(), // Columna FECHA/HORA
                        totalVenta            // Columna TOTAL
                    });
                }
            }
            
            // 6. Mostrar el gran total formateado
            // Usamos un formato de moneda
            DecimalFormat df = new DecimalFormat("$ #,##0.00");
            txtTotalDia.setText(df.format(granTotal));
            
            // 7. Avisar si no hubo ventas
            if (modeloTabla.getRowCount() == 0) {
                 JOptionPane.showMessageDialog(this, "No se encontraron ventas para la fecha seleccionada.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                 txtTotalDia.setText("$ 0.00");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + e.getMessage(), "Error SQL", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error en calcularCorte: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JDateChooser = new com.toedter.calendar.JDateChooser();
        CALCULAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentasDia = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTotalDia = new javax.swing.JTextField();

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setOpaque(false);

        JDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CALCULAR.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CALCULAR.setText("jButton1");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPORTE DE VENTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(302, 302, 302))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CALCULAR, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CALCULAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
        );

        jPanel2.setOpaque(false);

        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tablaVentasDia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tablaVentasDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FOLIO", "FECHA/HORA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tablaVentasDia);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("TOTAL VENDIDO:");

        txtTotalDia.setEditable(false);
        txtTotalDia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtTotalDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalDiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(732, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalDia, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(103, 103, 103))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalDia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTotalDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalDiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCULAR;
    private com.toedter.calendar.JDateChooser JDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVentasDia;
    private javax.swing.JTextField txtTotalDia;
    // End of variables declaration//GEN-END:variables
}
